openapi: 3.0.1
info:
  title: Logistics API Documentation
  description: This is logistics API
  version: 0.0.1
servers:
- url: https://dev-api-booking-logistics.apps.kpc-dev.com
  description: Development Server
- url: https://pd1-api-booking-logistics.apps.kpc-dev.com
  description: PD1 Server
- url: http://localhost:3000/
  description: Local Server
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
tags:
- name: order
  description: Everything about your Booking order
- name: logistics
  description: Everything about your Logistics Provider
- name: scheduler
  description: Scheduler App Logic

paths:
  /logistics/assort-code:
    post:
      tags:
          - logistics
      summary: Returns sortingCode from remote area SCG.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        description: Get sortingcode from SCG express
        content:
          'application/json':
            schema:
              required:
                - postalCode
                - address
              type: object
              properties:
                postalCode:
                  type: string
                  default : 23000
                address:
                  type: string
                  default : 19/21 หมู่ 10 เกาะกูด
      responses:
        200:
          description: object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  postalCode:
                    type: string
                    example: 23000
                  assortCode:
                    type: string
                    example: 204-07-88   
  /logistics/history-logs:
    get:
      tags:
        - logistics
      summary: Returns History Log.
      security:
        - BearerAuth: []
      description: Get History Log by query
      parameters:
        - in: query
          name: trackingNumber
          schema: 
            type : string
        - in: query
          name: actionType
          schema:
            type : string
            enum: [OUTBOUND, INBOUND, UPDATE_STATUS]
        - in: query
          name: courier
          schema:
            type : string
            enum: [scg-express, cj, kerry]
        - in: query
          name: platform
          schema:
            type : string
            enum: [firster]
        - in: query
          name: sortBy
          schema:
            type : string
            enum: [created_date]
        - in: query
          name: sortType
          schema:
            type : string
            enum: [asc,desc]
      responses: 
        200:
          description: object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array

  /order:
    post:
      tags:
        - order
      summary: Create Booking Logistics Order
      security:
        - BearerAuth: []
      requestBody:
        required: true
        description: xxxxxxxxx
        content:
          'application/json':
            schema:
              required:
                - orderId
                - shipperCode
                - providerCode
                - senderContactInfo
                - customerContactInfo
                - totalBoxes
                - platform
                - trackingNumber
              type: object
              properties:
                orderId:
                  type: string
                  example : 'xxxx-1'
                shipperCode:
                  type: string
                  example : '00214110143'
                providerCode:
                  type: string
                  example : 'scg-express'
                senderContactInfo:
                  required:
                  - name
                  - phone
                  - address
                  - postalCode
                  type: object
                  properties:
                    name:
                      type: string
                      example : 'Firster Co.,Ltd.'
                    phone:
                      type: string
                      example : '021111111'
                    address:
                      type: string
                      example : 'ใต้หล้าฟ้าเขียว'
                    postalCode:
                      type: string
                      example : '10100'
                customerContactInfo:
                  required:
                  - name
                  - phone
                  - address
                  - postalCode
                  type: object
                  properties:
                    name:
                      type: string
                      example : 'birdbida'
                    phone:
                      type: string
                      example : '0898888888'
                    address:
                      type: string
                      example : 'ยุทธภพ'
                    postalCode:
                      type: string
                      example : '10250'
                totalBoxes:
                  required:
                  type: integer
                  example : 1
                platform:
                  type: string
                  example : 'firster'
                trackingNumber:
                  type: string
                  example : 'xxxx-1#1'
                netSale:
                  type: number
                  example: 20000.5
      responses:
        200:
          description: Created Successfully
          content: 
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
  /order/get-status:
    post:
      tags:
        - order
      summary: Get Order Status By Tracking Numbers
      security:
        - BearerAuth: []
      requestBody:
        required: true
        description: Get Order Status By Tracking Numbers
        content:
          'application/json':
            schema:
              required:
                - platform
                - trackingNumbers
              type: object
              properties:
                platform:
                  type: string
                  example : 'firster'
                trackingNumbers:
                  type: array
                  example : ['xxxx-1#1','xxxx-2#1']
                  items:
                    type: string
      responses:
        200:
          description: Created Successfully
          content: 
            application/json:
              schema:
                type: object
                properties:
                  successfulItems:
                    type: array
                    items: 
                      type: object
                      properties:
                        trackingNumber:
                          type: string
                        orderStatus:
                          type: string
                  failedItems:
                    type: array
                    items: 
                      type: object
                      properties:
                        trackingNumber:
                          type: string
                        errorMessage:
                          type: string
      x-codegen-request-body-name: body
  /order/hooks-status-platform:
    put:
      tags:
        - order
      summary: Hooks Order status from Platform
      security:
        - BearerAuth: []
      requestBody:
        required: true
        description: Hooks Order status from Platform
        content:
          'application/json':
            schema:
              required:
                - trackingNumber
                - statusName
              type: object
              properties:
                trackingNumber:
                  type: string
                  example : 'xxxx-1#1'
                statusName:
                  type: string
                  example : 'canceled_cn'         
      responses:
        200:
          description: Update Successfully
          content: 
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
  /order/hooks-status-orders:
    post:
      tags:
        - order
      summary: Hooks Order Status from Logistics Provider
      security:
        - BearerAuth: []
      requestBody:
        required: true
        description: Hooks Order Status from Logistics Provider
        content:
          'application/json':
            schema:
              required:
                - invoice_no
                - code
                - status_name
              type: object
              properties:
                invoice_no:
                  type: string
                  example : 'xxxx-1#1'
                code:
                  type: string
                  example : '90'
                status_name: 
                  type: string
                  example : 'Item has been delivered.'
                datetime: 
                  type: number
                  example : '2019-10-30 19:27:00'
                delivery_fee: 
                  type: string
                  example : 77.77
                Item_Size: 
                  type: string
                  example : '0107'
      responses:
        200:
          description: Update Successfully
          content: 
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
      x-codegen-request-body-name: body
  /order/kerry/shipment_status:
    post:
      tags:
        - order
      summary: Hooks Order Status from Kerry Provider
      parameters:
        - in: header
          name: app-id
        - in: header
          name: app-key
      requestBody:
        required: true
        description: Hooks Order Status from Kerry Provider
        content:
          'application/json':
            schema:
              type: object
              properties:
                req:
                  type: array
                  items:
                    type: object
                    properties:
                      status:
                        required:
                          - con_no
                          - status_code
                          - status_desc
                          - status_date
                          - update_date
                          - ref_no
                          - r
                          - location
                          - location_code
                          - location_postcode
                        type: object
                        properties:
                          con_no:
                            type: string
                            example: 'KERRY00000001'
                          status_code:
                            type: string
                            example: '010'
                          status_desc:
                            type: string
                            example: 'Shipment picked-up'
                          status_date:
                            type: string
                            example: '2023-03-03 10:00:00'
                          update_date:
                            type: string
                            example: '2023-03-03 10:00:00'
                          ref_no:
                            type: string
                            example: '0000000000000ABCDEFG'
                          r:
                            type: string
                            example: '1'
                          location:
                            type: string
                            example: 'กรุงเทพมหานคร, พระราม 2'
                          location_code:
                            type: string
                            example: 'THR2M'
                          location_postcode:
                            type: string
                            example: '10150'
                          geo:
                            type: string
                            example: '18.0970883,99'
                          signature:
                            type: string
                            example: '{POD Photo URL}'
                          Return_Consignment_No:
                            type: string
                            example: '2014773403RTN'
      responses:
        200:
          description: Successfully
          content: 
            application/json:
              schema:
                type: object
                properties:
                  res:
                    type: object
                    properties:
                      status:
                        type: object
                        properties:
                          status_code:
                            type: string
                            example: '000'
                          status_desc:
                            type: string
                            example: 'Successful'
      x-codegen-request-body-name: body

  /order/booking-ready-orders:
    post:
      tags:
        - scheduler
      summary: Scheduler Booking Orders to Logistics Provider
      security:
        - BearerAuth: []
      requestBody:
        required: true
        description: Scheduler Booking Orders to Logistics Provider
        content:
          'application/json':
            schema:
              required:
                - platform
              type: object
              properties:
                platform:
                  type: string
                  example : 'firster' 
      responses:
        200:
          description: Successfully                
      x-codegen-request-body-name: body
  /order/recheck-unmoving-orders:
    post:
      tags:
        - scheduler
      summary: Scheduler recheck Unmoving Orders from Logistics Provider
      security:
        - BearerAuth: []
      requestBody:
        required: true
        description: Scheduler recheck Unmoving Orders from Logistics Provider
        content:
          'application/json':
            schema:
              required:
                - platform
                - unmovingHourRatio
              type: object
              properties:
                platform:
                  type: string
                  example : 'firster' 
                unmovingHourRatio:
                  type: number
                  example : 36
      responses:
        200:
          description: Successfully                
      x-codegen-request-body-name: body